runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
